# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd1dbdb172fca8be3bc7783e3ba44a2959e2bab88f337fd0861a1c3bf397c941993737fb0c6a04bbfd5a69fa78c96f2e577ef1f86e3d17febbe371d78b19b8c4

test:
  secret_key_base: 75a05179daa0aa5b090154bd8fbdfd05117b01fb08d1a688ed3b970dfe2ed7c42dd3ce490c2cefab8bc73050a3cf6f34320041fb00a3f7ceed7167a0daf7b702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
